default: &default
  cran_site_url: <%= ENV.fetch("CRAN_SITE_URL", "https://cran.r-project.org/src/contrib") %>
  sidekiq_redis_url: <%= ENV.fetch('SIDEKIQ_REDIS_URL', 'redis://localhost:6379/1')%>
development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
